- pipeline.id: es_walletbackend_es_kafka
  path.config: "/usr/share/logstash/pipeline/es_kafka.conf"
  pipeline.workers: 1
- pipeline.id: es_walletbackend_kafka_hdfs
  path.config: "/usr/share/logstash/pipeline/kafka_mongo.conf"