- pipeline.id: es_example_es_kafka
  path.config: "/usr/share/logstash/pipeline/es_kafka.conf"
  pipeline.workers: 1
- pipeline.id: es_example_kafka_hdfs
  path.config: "/usr/share/logstash/pipeline/kafka_hdfs.conf"