ARG VERSION=6.8.5
FROM docker.elastic.co/logstash/logstash:$VERSION
ARG FOLDER=config

MAINTAINER Chau.Tran <chauamtran@gmail.com>
USER root

COPY config/$FOLDER /usr/share/logstash/pipeline/
COPY config/$FOLDER/logstash.yml /usr/share/logstash/config/logstash.yml
COPY config/$FOLDER/pipelines.yml /usr/share/logstash/config/pipelines.yml
COPY lib/logstash-offline-mongodb-6.8.5.zip /usr/share/logstash/$FOLDER/logstash-offline-mongodb-6.8.5.zip

RUN rm -f /usr/share/logstash/pipeline/logstash.conf && \
    logstash-plugin install file:///usr/share/logstash/$FOLDER/logstash-offline-mongodb-6.8.5.zip && \
    export LS_JAVA_OPTS="-Xmx2g -Xms1g" && \
    export LS_JAVA_OPTS="-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ $LS_JAVA_OPTS"

CMD logstash --config.reload.automatic