- pipeline.id: mysql_merchant_mysql_kafka
  path.config: "/usr/share/logstash/pipeline/mysql_kafka.conf"
  pipeline.workers: 1
- pipeline.id: mysql_merchant_kafka_hdfs
  path.config: "/usr/share/logstash/pipeline/kafka_mongo.conf"